apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonstop-server-deployment
  labels:
    app: nonstop-server-deployment
  annotations:
    kubernetes.io/change-cause: version 0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonstop-server-deployment
  strategy:
    rollingUpdate:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nonstop-server-deployment
    spec:
      initContainers:
      - name: check-pod
        image: nicolaka/netshoot
        command: 
        - curl
        - clusterip-service
      containers:
      - name: nonstop-server-deployment
        image: tndyd5390/nonstop-server:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      terminationGracePeriodSeconds: 10
