apiVersion: v1
kind: Service
metadata:
  name: nonstop-server-service
spec:
  type: NodePort
  selector:
    app: nonstop-server-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
