apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonstop-server-deployment
  # annotations:
    # kubernetes.io/change-cause: version 1.10.1
spec:
  replicas: 10
  selector:
    matchLabels:
      run: nonstop-server-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nonstop-server-deployment
    spec:
      containers:
      - name: nonstop-server-deployment
        image: tndyd5390/nonstop-server:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      terminationGracePeriodSeconds: 10
